package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataObjectTest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "pointConcept")
   private eu.trentorise.game.model.PointConcept pointConcept;

   public DataObjectTest()
   {
   }

   public eu.trentorise.game.model.PointConcept getPointConcept()
   {
      return this.pointConcept;
   }

   public void setPointConcept(
         eu.trentorise.game.model.PointConcept pointConcept)
   {
      this.pointConcept = pointConcept;
   }

   public DataObjectTest(eu.trentorise.game.model.PointConcept pointConcept)
   {
      this.pointConcept = pointConcept;
   }

}