package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PointConcept implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("score")
   private java.lang.Double score;

   @org.kie.api.definition.type.Label(value = "test")
   private java.lang.Byte test;

   public PointConcept()
   {
   }

   public java.lang.Double getScore()
   {
      return this.score;
   }

   public void setScore(java.lang.Double score)
   {
      this.score = score;
   }

   public java.lang.Byte getTest()
   {
      return this.test;
   }

   public void setTest(java.lang.Byte test)
   {
      this.test = test;
   }

   public PointConcept(java.lang.Double score, java.lang.Byte test)
   {
      this.score = score;
      this.test = test;
   }

}