package com;

import eu.trentorise.game.model.PointConcept;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PointConcept implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("score")
   private java.lang.Double score;

   @org.kie.api.definition.type.Label("test")
   private PointConcept test;

   public PointConcept()
   {
   }

   public java.lang.Double getScore()
   {
      return this.score;
   }

   public void setScore(java.lang.Double score)
   {
      this.score = score;
   }

   public eu.trentorise.game.model.PointConcept getTest()
   {
      return this.test;
   }

   public void setTest(eu.trentorise.game.model.PointConcept test)
   {
      this.test = test;
   }

   public PointConcept(java.lang.Double score,
         eu.trentorise.game.model.PointConcept test)
   {
      this.score = score;
      this.test = test;
   }

}