package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PointConcept implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "score")
   private java.lang.Double score;

   public PointConcept()
   {
   }

   public java.lang.Double getScore()
   {
      return this.score;
   }

   public void setScore(java.lang.Double score)
   {
      this.score = score;
   }

   public PointConcept(java.lang.Double score)
   {
      this.score = score;
   }

}