package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "test")
   private eu.trentorise.game.model.PointConcept test;

   public Test()
   {
   }

   public eu.trentorise.game.model.PointConcept getTest()
   {
      return this.test;
   }

   public void setTest(eu.trentorise.game.model.PointConcept test)
   {
      this.test = test;
   }

   public Test(eu.trentorise.game.model.PointConcept test)
   {
      this.test = test;
   }

}